[theme]
primaryColor = "#FF0000"             # bright red buttons
backgroundColor = "#000000"          # black page
secondaryBackgroundColor = "#222222" # dark panels
textColor = "#00FF00"                # green text
font = "serif"
